# Generated by Django 2.2.3 on 2019-08-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190812_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('News', 'News'), ('Savoir', 'Savoir')], default=0, max_length=255),
        ),
    ]
