# Generated by Django 2.2.4 on 2019-08-20 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Post2',
        ),
    ]
