# Generated by Django 2.2.4 on 2019-10-14 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0002_auto_20190820_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post2',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post2',
            name='status',
        ),
    ]
